quarkus.http.port=${PORT:3000}
quarkus.http.cors.enabled=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/linux_distro_roguelite_promotion}
quarkus.datasource.jdbc.max-size=8
quarkus.log.category."dev.frederik.promotion".level=INFO

quarkus.mailer.host=${SMTP_HOST:mail.fretux.ch}
quarkus.mailer.port=${SMTP_PORT:587}
quarkus.mailer.username=${SMTP_USER:no-reply@fretux.ch}
quarkus.mailer.password=${SMTP_PASS:}
quarkus.mailer.from=${MAIL_FROM:Fretux <no-reply@fretux.ch>}
quarkus.mailer.tls=${SMTP_SECURE:false}
quarkus.mailer.start-tls=REQUIRED
registration.base-url=${BASE_URL:http://localhost:3000}
registration.token-secret=${TOKEN_SECRET:}

auth.admin.username=${ADMIN_USERNAME:admin}
auth.admin.password=${ADMIN_PASSWORD:admin}

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://kernel-panic.local/issuer
mp.jwt.token.header=Authorization
mp.jwt.token.signed=true
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.smallrye-jwt.enabled=true

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.oauth2-redirect-url=/q/oauth2-redirect.html
mp.openapi.extensions.smallrye.security-scheme.name=BearerAuth
mp.openapi.extensions.smallrye.security-scheme.type=HTTP
mp.openapi.extensions.smallrye.security-scheme.scheme=bearer
mp.openapi.extensions.smallrye.security-scheme.bearer-format=JWT
